# tekton/00-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa           # name sa
  namespace: banking-demo
---
# quyền edit
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-sa-edit
  namespace: banking-demo
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: banking-demo
roleRef:
  kind: ClusterRole
  name: edit                  # Role edit : tạo, sửa, xóa
  apiGroup: rbac.authorization.k8s.io
---
# quyền build image
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-sa-buildconfig
  namespace: banking-demo
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: banking-demo
roleRef:
  kind: ClusterRole
  name: system:image-builder  # Quyền push image vào imageStream
  apiGroup: rbac.authorization.k8s.io