# tekton/02-pipeline.yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: banking-deploy-pipeline
  namespace: banking-demo
spec:
  params:
    - name: GIT_COMMIT
      type: string
      description: Git commit SHA, dùng làm image tag
      default: latest
    - name: GIT_BRANCH
      type: string
      description: Git branch name
      default: main

  tasks:
    - name: build-backend
      taskRef:
        name: build-backend
      params:
        - name: IMAGE_TAG
          value: $(params.GIT_COMMIT)

    - name: build-frontend
      taskRef:
        name: build-frontend
      params:
        - name: IMAGE_TAG
          value: $(params.GIT_COMMIT)

    - name: deploy-and-verify
      taskRef:
        name: deploy-and-verify
      params:
        - name: IMAGE_TAG
          value: $(params.GIT_COMMIT)
      runAfter:
        - build-backend
        - build-frontend
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: banking-backend-deploy-pipeline
  namespace: banking-demo
spec:
  params:
    - name: GIT_COMMIT
      type: string
      description: Git commit SHA, dùng làm image tag
      default: latest
    - name: GIT_BRANCH
      type: string
      description: Git branch name
      default: main

  tasks:
    - name: build-backend
      taskRef:
        name: build-backend
      params:
        - name: IMAGE_TAG
          value: $(params.GIT_COMMIT)

    - name: deploy-and-verify-backend
      taskRef:
        name: deploy-and-verify-backend
      params:
        - name: IMAGE_TAG
          value: $(params.GIT_COMMIT)
      runAfter:
        - build-backend
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: banking-frontend-deploy-pipeline
  namespace: banking-demo
spec:
  params:
    - name: GIT_COMMIT
      type: string
      description: Git commit SHA, dùng làm image tag
      default: latest
    - name: GIT_BRANCH
      type: string
      description: Git branch name
      default: main

  tasks:
    - name: build-frontend
      taskRef:
        name: build-frontend
      params:
        - name: IMAGE_TAG
          value: $(params.GIT_COMMIT)

    - name: deploy-and-verify-frontend
      taskRef:
        name: deploy-and-verify-frontend
      params:
        - name: IMAGE_TAG
          value: $(params.GIT_COMMIT)
      runAfter:
        - build-frontend