# tekton/04-pipelinerun-manual.yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: banking-deploy-manual-
  namespace: banking-demo
spec:
  pipelineRef:
    name: banking-deploy-pipeline
  serviceAccountName: pipeline-sa
  params:
    - name: GIT_COMMIT
      value: manual-test
    - name: GIT_BRANCH
      value: main